image: elizabethdev/gitpod:sinope_neon

jetbrains:
  intellij:
    prebuilds:
      version: both
    plugins:
      - com.github.copilot
      - com.intellij.lang.jsgraphql

tasks:
  - init: yarn install
    command: yarn run dev
