image: elizabethdev/gitpod:sinope_ask

jetbrains:
  intellij:
    prebuilds:
      version: both
    plugins:
      - com.github.copilot

tasks:
  - init: yarn install && yarn run build
    command: yarn run dev
